version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: retail_db
      MYSQL_USER: retail_user
      MYSQL_PASSWORD: retail_pass
    ports:
      - "3306:3306"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: retail_user
      POSTGRES_PASSWORD: retail_pass
      POSTGRES_DB: retail_db
    ports:
      - "5432:5432"
